name: Master workflow

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
#     runs-on: ubuntu-20.04
    runs-on: self-hosted
    env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ROLLBAR_TOKEN: ${{ secrets.ROLLBAR_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        extensions: mbstring, intl, xml, curl, zip, dom, json, openssl, sqlite3
        coverage: xdebug        
        tools: php-cs-fixer, phpunit

    - name: Setup project
      run: make setup

    - name: Check lint
      run: make lint

    - name: Run test & publish code coverage
      uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        XDEBUG_MODE: 'coverage'
      with:
        coverageCommand: make coverage
        debug: true
