name: Master workflow

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ROLLBAR_TOKEN: ${{ secrets.ROLLBAR_TOKEN }}
    steps:
    - uses: actions/checkout@v1

    - name: PHP Security Checker
      uses: StephaneBour/actions-php-security-checker@1.1

    - name: Setup project
      run: make setup

    - name: Check lint
      run: make lint
      
    - name: download & run test reporter before-build
    - run: | 
        curl -o ./cc-test-reporter -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: make test
    
    - name: run test reporter after-build
      run: cc-test-reporter after-build
